#pragma once

#define DEFAULT_FRAME_DWSPEED 50

#define PLAYER_IDLE_TO_RUN_FCX 40
#define PLAYER_IDLE_TO_RUN_FCY 38

#define PLAYER_ROLL_FCX 54
#define PLAYER_ROLL_FCY 34

#define PLAYER_IDLE_FCX 36
#define PLAYER_IDLE_FCY 40


#define PLAYER_RUN_TO_IDLE_FCX 38
#define PLAYER_RUN_TO_IDLE_FCY 38

#define PLAYER_IDLE_TO_SNEAK_FCX 42
#define PLAYER_IDLE_TO_SNEAK_FCY 38

#define PLAYER_JUMP_FCX 32
#define PLAYER_JUMP_FCY 44

#define PLAYER_RUN_FCX	46
#define PLAYER_RUN_FCY	38

#define PLAYER_CROUCH_FCX	37
#define PLAYER_CROUCH_FCY	38

#define PLAYER_ATTACK_FCX	67
#define PLAYER_ATTACK_FCY	37

#define PLAYER_NORMAL_ATTACK_EFFECT_FCX 123
#define PLAYER_NORMAL_ATTACK_EFFECT_FCY 30

#define PLAYER_FALL_FCX 36
#define PLAYER_FALL_FCY 45

#define PLAYER_WALL_GRAB_FCX 29
#define PLAYER_WALL_GRAB_FCY 42

#define PLAYER_FLIP_FCX 52
#define PLAYER_FLIP_FCY 48

#define RANGE_FCX 452
#define RANGE_FCY 452

#define RANGE_CHAR_FCX 67
#define RANGE_CHAR_FCY 37

#define RANGE_RUSH_FCX 108
#define RANGE_RUSH_FCY 31

#define GRUNT_IDLE_FCX	30
#define GRUNT_IDLE_FCY  36

#define GRUNT_WALK_FCX 32
#define GRUNT_WALK_FCY 40

#define GRUNT_CHASE_FCX 36
#define GRUNT_CHASE_FCY 39

#define GRUNT_ATTACK_FCX 44
#define GRUNT_ATTACK_FCY 42

#define GANGSTER_IDLE_FCX 49
#define GANGSTER_IDLE_FCY 50

#define GANGSTER_WALK_FCX 34
#define GANGSTER_WALK_FCY 40

#define GANGSTER_CHASE_FCX 45
#define GANGSTER_CHASE_FCY 40

#define EXPLOSIVE_FCX 17
#define EXPLOSIVE_FCY 32

#define OIL_DRUM_FCX 21
#define OIL_DRUM_FCY 27

#define EXPLOSION_FCX 50
#define EXPLOSION_FCY 43

#define GANGSTER_DEAD_FCX 44
#define GANGSTER_DEAD_FCY 34

#define GRUNT_DEAD_FCX	56
#define GRUNT_DEAD_FCY	41

#define POMP_IDLE_FCX	33
#define POMP_IDLE_FCY	42

#define POMP_CHASE_FCX	33
#define POMP_CHASE_FCY	40

#define POMP_ATTACK_FCX	46
#define POMP_ATTACK_FCY 43

#define POMP_WALK_FCX	31
#define POMP_WALK_FCY	43

#define POMP_DEAD_FCX	54
#define POMP_DEAD_FCY	42

#define TILECX	16
#define TILECY	16

#define BOSS_IDLE_FCX	44
#define BOSS_IDLE_FCY	86

#define BOSS_DRAW_GUN_FCX	76
#define BOSS_DRAW_GUN_FCY	86

#define BOSS_AIM_FCX	78
#define BOSS_AIM_FCY	104

#define BOSS_RECOVER_FCX	140
#define BOSS_RECOVER_FCY	106

#define BLOOD_0_FCX		53
#define BLOOD_0_FCY		63

#define BLOOD_1_FCX		54
#define BLOOD_1_FCY		70

#define BLOOD_2_FCX		96
#define BLOOD_2_FCY		27

#define BLOOD_3_FCX		32
#define BLOOD_3_FCY		32


#define DOOR_FCX 80
#define DOOR_FCY 64

#define PLAYER_DOOR_KICK_FCX	54
#define PLAYER_DOOR_KICK_FCY	38

#define BOSS_TELEPORT_FCX		56
#define BOSS_TELEPORT_FCY		90

#define BOSS_TELEPORT_GROUND_FCX	82
#define BOSS_TELEPORT_GROUND_FCY	70

#define LAZER_WIDTH 1000
#define LAZER_HEIGHT 25

#define BULLET_REFLECT_EFFECT_FCX	70
#define BULLET_REFLECT_EFFECT_FCY	64

#define ENEMY_FOLLOW_FCX	17
#define ENEMY_FOLLOW_FCY	20

#define ITEM_ARROW_FCX	18
#define ITEM_ARROW_FCY	21

#define RUN_DUST_FCX	56
#define RUN_DUST_FCY	23

#define TAKE_OUT_GUN_FCX	94
#define TAKE_OUT_GUN_FCY	86

#define SHOOT_GUN_FCX		136
#define SHOOT_GUN_FCY		92

#define GERNADE_FCX			14
#define GERNADE_FCY			18

#define GERNADE_CIRCLE_FCX		274
#define GERNADE_CIRCLE_FCY		274

#define BOSS_JUMP_FCX			54
#define BOSS_JUMP_FCY			88

#define BOSS_WALL_GRAB_FCX		60
#define BOSS_WALL_GRAB_FCY		86

#define BOSS_WALL_JUMP_FCX		108
#define BOSS_WALL_JUMP_FCY		124

#define BOSS_OUT_PATTERN_FCX	72
#define BOSS_OUT_PATTERN_FCY	62

#define BOSS_IN_PATTERN_FCX		72
#define BOSS_IN_PATTERN_FCY		62

#define PLAYER_LAY_DOWN_FCX		65
#define PLAYER_LAY_DOWN_FCY		27

#define PLAYER_LAY_DOWN_START_FCX	35
#define PLAYER_LAY_DOWN_START_FCY	38

#define PLAYER_LAY_DOWN_MIDDLE_FCX	41
#define PLAYER_LAY_DOWN_MIDDLE_FCY	29

#define BOSS_LAY_DOWN_FCX		116
#define BOSS_LAY_DOWN_FCY		82

#define BOSS_DEAD_BODY_FCX	112
#define BOSS_DEAD_BODY_FCY	42


#define BOSS_DEAD_BODY_NO_HEAD_FCX	120
#define BOSS_DEAD_BODY_NO_HEAD_FCY	44

#define THUNDER_BREATHING_SKILL_EFFECT_FCX		800
#define THUNDER_BREATHING_SKILL_EFFECT_FCY		176
